// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Siv.Persistence;

#nullable disable

namespace Siv.Persistence.Migraciones
{
    [DbContext(typeof(SivDbContext))]
    [Migration("20260801000000_CreacionInicial")]
    partial class CreacionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Siv.Domain.Entidades.Aerolinea", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("AerolineaId")
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.HasKey("Id");

                b.HasIndex("Codigo")
                    .IsUnique();

                b.ToTable("Aerolineas");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.Aeropuerto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("AeropuertoId")
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Ciudad")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Pais")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.HasIndex("Codigo")
                    .IsUnique();

                b.ToTable("Aeropuertos");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.Auditoria", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("AuditoriaId")
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Accion")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Tabla")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("Fecha")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Auditorias");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.EstadoVuelo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("EstadoVueloId")
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.HasIndex("Nombre")
                    .IsUnique();

                b.ToTable("EstadosVuelo");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.Vuelo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("VueloId")
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("NumeroVuelo")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<int>("AerolineaId")
                    .HasColumnType("int");

                b.Property<int>("AeropuertoOrigenId")
                    .HasColumnType("int");

                b.Property<int>("AeropuertoDestinoId")
                    .HasColumnType("int");

                b.Property<DateTime>("HorarioProgramado")
                    .HasColumnType("datetime2");

                b.Property<string>("Puerta")
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.Property<int>("EstadoVueloId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("NumeroVuelo")
                    .IsUnique();

                b.HasIndex("AerolineaId");

                b.HasIndex("AeropuertoOrigenId");

                b.HasIndex("AeropuertoDestinoId");

                b.HasIndex("EstadoVueloId");

                b.ToTable("Vuelos");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.CambioOperativo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("CambioOperativoId")
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("VueloId")
                    .HasColumnType("int");

                b.Property<string>("TipoCambio")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Causa")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("FechaCambio")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("VueloId");

                b.ToTable("CambiosOperativos");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.HistorialEstadoVuelo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("HistorialEstadoVueloId")
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("VueloId")
                    .HasColumnType("int");

                b.Property<int>("EstadoAnteriorId")
                    .HasColumnType("int");

                b.Property<int>("EstadoNuevoId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaCambio")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("VueloId");

                b.ToTable("HistorialEstados");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.Notificacion", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("NotificacionId")
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("VueloId")
                    .HasColumnType("int");

                b.Property<string>("Usuario")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Mensaje")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Leida")
                    .HasColumnType("bit")
                    .HasDefaultValue(false);

                b.Property<DateTime>("FechaEnvio")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("VueloId");

                b.ToTable("Notificaciones");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.Seguimiento", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("SeguimientoId")
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Usuario")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("VueloId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaSeguimiento")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("VueloId", "Usuario")
                    .IsUnique();

                b.ToTable("Seguimientos");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.Vuelo", b =>
            {
                b.HasOne("Siv.Domain.Entidades.Aerolinea", "Aerolinea")
                    .WithMany()
                    .HasForeignKey("AerolineaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Siv.Domain.Entidades.Aeropuerto", "AeropuertoOrigen")
                    .WithMany()
                    .HasForeignKey("AeropuertoOrigenId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Siv.Domain.Entidades.Aeropuerto", "AeropuertoDestino")
                    .WithMany()
                    .HasForeignKey("AeropuertoDestinoId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Siv.Domain.Entidades.EstadoVuelo", "EstadoVuelo")
                    .WithMany()
                    .HasForeignKey("EstadoVueloId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Aerolinea");
                b.Navigation("AeropuertoOrigen");
                b.Navigation("AeropuertoDestino");
                b.Navigation("EstadoVuelo");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.CambioOperativo", b =>
            {
                b.HasOne("Siv.Domain.Entidades.Vuelo", "Vuelo")
                    .WithMany()
                    .HasForeignKey("VueloId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Vuelo");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.HistorialEstadoVuelo", b =>
            {
                b.HasOne("Siv.Domain.Entidades.Vuelo", "Vuelo")
                    .WithMany()
                    .HasForeignKey("VueloId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Vuelo");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.Notificacion", b =>
            {
                b.HasOne("Siv.Domain.Entidades.Vuelo", "Vuelo")
                    .WithMany()
                    .HasForeignKey("VueloId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Vuelo");
            });

            modelBuilder.Entity("Siv.Domain.Entidades.Seguimiento", b =>
            {
                b.HasOne("Siv.Domain.Entidades.Vuelo", "Vuelo")
                    .WithMany()
                    .HasForeignKey("VueloId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Vuelo");
            });
#pragma warning restore 612, 618
        }
    }
}
